import { Lead } from "../types";
import { syncAllLeadsToPipeline } from "./pipelineSync";

// Função para gerar leads de exemplo
export function generateSampleLeads(): Lead[] {
  const today = new Date();
  const sampleLeads: Lead[] = [
    {
      id: 1,
      name: "Maria Silva",
      phone: "(11) 99999-8888",
      email: "maria.silva@email.com",
      status: "novo",
      source: "meta",
      date: formatDate(subtractDays(today, 2)),
      automations: [1, 2],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 2).toISOString(),
      updatedAt: subtractDays(today, 2).toISOString(),
    },
    {
      id: 2,
      name: "João Santos",
      phone: "(11) 98888-7777",
      email: "joao.santos@email.com",
      status: "contato",
      source: "google",
      date: formatDate(subtractDays(today, 1)),
      automations: [1],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 1).toISOString(),
      updatedAt: subtractDays(today, 1).toISOString(),
    },
    {
      id: 3,
      name: "Ana Costa",
      phone: "(11) 97777-6666",
      email: "ana.costa@email.com",
      status: "novo",
      source: "organico",
      date: formatDate(subtractDays(today, 3)),
      automations: [],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 3).toISOString(),
      updatedAt: subtractDays(today, 3).toISOString(),
    },
    {
      id: 4,
      name: "Pedro Oliveira",
      phone: "(11) 96666-5555",
      email: "pedro.oliveira@email.com",
      status: "fechado",
      source: "meta",
      date: formatDate(subtractDays(today, 5)),
      automations: [2],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 5).toISOString(),
      updatedAt: subtractDays(today, 5).toISOString(),
    },
    {
      id: 5,
      name: "Carla Mendes",
      phone: "(11) 95555-4444",
      email: "carla.mendes@email.com",
      status: "contato",
      source: "manual",
      date: formatDate(subtractDays(today, 4)),
      automations: [1, 3],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 4).toISOString(),
      updatedAt: subtractDays(today, 4).toISOString(),
    },
    {
      id: 6,
      name: "Lucas Ferreira",
      phone: "(11) 94444-3333",
      email: "lucas.ferreira@email.com",
      status: "perdido",
      source: "google",
      date: formatDate(subtractDays(today, 6)),
      automations: [],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 6).toISOString(),
      updatedAt: subtractDays(today, 6).toISOString(),
    },
    {
      id: 7,
      name: "Fernanda Alves",
      phone: "(11) 93333-2222",
      email: "fernanda.alves@email.com",
      status: "novo",
      source: "meta",
      date: formatDate(subtractDays(today, 1)),
      automations: [1],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 1).toISOString(),
      updatedAt: subtractDays(today, 1).toISOString(),
    },
    {
      id: 8,
      name: "Ricardo Souza",
      phone: "(11) 92222-1111",
      email: "ricardo.souza@email.com",
      status: "contato",
      source: "google",
      date: formatDate(subtractDays(today, 2)),
      automations: [1, 2],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 2).toISOString(),
      updatedAt: subtractDays(today, 2).toISOString(),
    },
    {
      id: 9,
      name: "Juliana Rocha",
      phone: "(11) 91111-0000",
      email: "juliana.rocha@email.com",
      status: "novo",
      source: "organico",
      date: formatDate(subtractDays(today, 0)),
      automations: [],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 0).toISOString(),
      updatedAt: subtractDays(today, 0).toISOString(),
    },
    {
      id: 10,
      name: "Marcos Lima",
      phone: "(11) 90000-9999",
      email: "marcos.lima@email.com",
      status: "fechado",
      source: "meta",
      date: formatDate(subtractDays(today, 7)),
      automations: [2],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 7).toISOString(),
      updatedAt: subtractDays(today, 7).toISOString(),
    },
    {
      id: 11,
      name: "Patricia Martins",
      phone: "(11) 89999-8888",
      email: "patricia.martins@email.com",
      status: "contato",
      source: "google",
      date: formatDate(subtractDays(today, 3)),
      automations: [1],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 3).toISOString(),
      updatedAt: subtractDays(today, 3).toISOString(),
    },
    {
      id: 12,
      name: "Roberto Castro",
      phone: "(11) 88888-7777",
      email: "roberto.castro@email.com",
      status: "novo",
      source: "manual",
      date: formatDate(subtractDays(today, 1)),
      automations: [],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 1).toISOString(),
      updatedAt: subtractDays(today, 1).toISOString(),
    },
    {
      id: 13,
      name: "Beatriz Nunes",
      phone: "(11) 87777-6666",
      email: "beatriz.nunes@email.com",
      status: "fechado",
      source: "meta",
      date: formatDate(subtractDays(today, 8)),
      automations: [1, 2],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 8).toISOString(),
      updatedAt: subtractDays(today, 8).toISOString(),
    },
    {
      id: 14,
      name: "Thiago Barbosa",
      phone: "(11) 86666-5555",
      email: "thiago.barbosa@email.com",
      status: "contato",
      source: "google",
      date: formatDate(subtractDays(today, 2)),
      automations: [1],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 2).toISOString(),
      updatedAt: subtractDays(today, 2).toISOString(),
    },
    {
      id: 15,
      name: "Camila Ribeiro",
      phone: "(11) 85555-4444",
      email: "camila.ribeiro@email.com",
      status: "novo",
      source: "organico",
      date: formatDate(subtractDays(today, 0)),
      automations: [],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 0).toISOString(),
      updatedAt: subtractDays(today, 0).toISOString(),
    },
    {
      id: 16,
      name: "Felipe Cardoso",
      phone: "(11) 84444-3333",
      email: "felipe.cardoso@email.com",
      status: "perdido",
      source: "meta",
      date: formatDate(subtractDays(today, 9)),
      automations: [],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 9).toISOString(),
      updatedAt: subtractDays(today, 9).toISOString(),
    },
    {
      id: 17,
      name: "Larissa Gomes",
      phone: "(11) 83333-2222",
      email: "larissa.gomes@email.com",
      status: "contato",
      source: "manual",
      date: formatDate(subtractDays(today, 4)),
      automations: [1, 3],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 4).toISOString(),
      updatedAt: subtractDays(today, 4).toISOString(),
    },
    {
      id: 18,
      name: "Gabriel Torres",
      phone: "(11) 82222-1111",
      email: "gabriel.torres@email.com",
      status: "novo",
      source: "google",
      date: formatDate(subtractDays(today, 1)),
      automations: [1],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 1).toISOString(),
      updatedAt: subtractDays(today, 1).toISOString(),
    },
    {
      id: 19,
      name: "Isabela Freitas",
      phone: "(11) 81111-0000",
      email: "isabela.freitas@email.com",
      status: "fechado",
      source: "meta",
      date: formatDate(subtractDays(today, 10)),
      automations: [2],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 10).toISOString(),
      updatedAt: subtractDays(today, 10).toISOString(),
    },
    {
      id: 20,
      name: "Rafael Dias",
      phone: "(11) 80000-9999",
      email: "rafael.dias@email.com",
      status: "contato",
      source: "organico",
      date: formatDate(subtractDays(today, 3)),
      automations: [1, 2],
      tags: [],
      customFields: {},
      createdAt: subtractDays(today, 3).toISOString(),
      updatedAt: subtractDays(today, 3).toISOString(),
    },
  ];

  return sampleLeads;
}

// Função auxiliar para subtrair dias de uma data
function subtractDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setDate(result.getDate() - days);
  return result;
}

// Função auxiliar para formatar data no formato brasileiro
function formatDate(date: Date): string {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  return `${day}/${month}/${year}`;
}

// Função para salvar os leads de exemplo no localStorage
export function saveSampleLeads(): void {
  const sampleLeads = generateSampleLeads();
  localStorage.setItem("leads", JSON.stringify(sampleLeads));
  
  // Sincronizar todos os leads com o Pipeline
  syncAllLeadsToPipeline();
  
  console.log(`✅ ${sampleLeads.length} leads de exemplo foram criados e salvos no sistema!`);
}

