import prisma from '../config/database.js';
import { logger } from '../utils/logger.js';
import { DealStage } from '@prisma/client';
import { generateObject } from 'ai';
import { z } from 'zod';
import {
  getActiveModel,
  isAIEnabled,
  logAiUsage,
  aiUnavailableError,
  resolveProviderConfig,
} from './aiProvider.js';

/**
 * AI-2.1 — Close-propensity score per deal (0-100), generated by AI based on:
 * time in current stage, number of interactions, last contact date, deal value
 * and the assignee's historical win rate. Result is stored on the Deal
 * (aiScore / aiScoreUpdatedAt / aiScoreFactors).
 *
 * Edge case: deals with missing data (no interactions, assignee without win-rate
 * history) are still scored; the affected factors are flagged "dados insuficientes".
 */

export interface ScoreFactor {
  label: string;
  detail: string;
}

export interface DealAIScore {
  score: number; // 0-100
  factors: ScoreFactor[]; // top 3
  updatedAt: string;
  aiGenerated: boolean;
}

const INSUFFICIENT = 'dados insuficientes';

function daysSince(date: Date | null | undefined): number | null {
  if (!date) return null;
  return Math.floor((Date.now() - new Date(date).getTime()) / (1000 * 60 * 60 * 24));
}

const scoreSchema = z.object({
  score: z.number().min(0).max(100).describe('Probabilidade de fechamento de 0 a 100'),
  factors: z
    .array(
      z.object({
        label: z.string().describe('Nome curto do fator'),
        detail: z.string().describe('Explicação curta; use "dados insuficientes" quando faltar dado'),
      })
    )
    .describe('Os 3 fatores principais que influenciam o score'),
});

const SCORE_SYSTEM_PROMPT = `Você é um analista de vendas que estima a probabilidade de fechamento de um deal (0 a 100).
Baseie-se SOMENTE nas métricas fornecidas: tempo no estágio atual, número de interações, dias desde o último contato, valor do deal e win rate do responsável.
Regras:
- Retorne um score inteiro de 0 a 100 e exatamente os 3 fatores mais influentes.
- Quando uma métrica vier marcada como "dados insuficientes", reflita isso no fator correspondente e seja conservador.
- Não invente dados que não foram fornecidos.`;

interface DealMetrics {
  name: string;
  value: number;
  stage: DealStage;
  probability: number;
  daysInStage: number | null;
  interactionCount: number;
  daysSinceLastContact: number | null;
  assigneeWinRate: number | null;
  assigneeClosedCount: number;
}

async function buildDealMetrics(tenantId: string, dealId: string): Promise<{ metrics: DealMetrics } | null> {
  const deal = await prisma.deal.findFirst({
    where: { id: dealId, tenantId },
    select: {
      name: true,
      value: true,
      stage: true,
      probability: true,
      assignedTo: true,
      updatedAt: true,
    },
  });
  if (!deal) return null;

  const [interactionCount, lastInteraction, currentStageHistory] = await Promise.all([
    prisma.interaction.count({ where: { dealId, tenantId } }),
    prisma.interaction.findFirst({
      where: { dealId, tenantId },
      orderBy: { createdAt: 'desc' },
      select: { createdAt: true },
    }),
    prisma.dealStageHistory.findFirst({
      where: { dealId, stage: deal.stage, exitedAt: null },
      orderBy: { enteredAt: 'desc' },
      select: { enteredAt: true },
    }),
  ]);

  // Time in current stage: from stage-history entry, else fall back to updatedAt.
  const daysInStage = daysSince(currentStageHistory?.enteredAt ?? deal.updatedAt);

  // Assignee win rate from their closed deals (WON / (WON + LOST)).
  let assigneeWinRate: number | null = null;
  let assigneeClosedCount = 0;
  if (deal.assignedTo) {
    const [won, lost] = await Promise.all([
      prisma.deal.count({ where: { tenantId, assignedTo: deal.assignedTo, stage: DealStage.WON } }),
      prisma.deal.count({ where: { tenantId, assignedTo: deal.assignedTo, stage: DealStage.LOST } }),
    ]);
    assigneeClosedCount = won + lost;
    if (assigneeClosedCount > 0) {
      assigneeWinRate = Math.round((won / assigneeClosedCount) * 100);
    }
  }

  return {
    metrics: {
      name: deal.name,
      value: Number(deal.value),
      stage: deal.stage,
      probability: deal.probability,
      daysInStage,
      interactionCount,
      daysSinceLastContact: daysSince(lastInteraction?.createdAt),
      assigneeWinRate,
      assigneeClosedCount,
    },
  };
}

function renderMetrics(m: DealMetrics): string {
  const fmtBRL = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(m.value);
  return [
    `Deal: ${m.name}`,
    `Estágio atual: ${m.stage}`,
    `Probabilidade informada pelo vendedor: ${m.probability}%`,
    `Valor do deal: ${fmtBRL}`,
    `Tempo no estágio atual: ${m.daysInStage === null ? INSUFFICIENT : `${m.daysInStage} dia(s)`}`,
    `Número de interações: ${m.interactionCount}`,
    `Dias desde o último contato: ${m.daysSinceLastContact === null ? `${INSUFFICIENT} (sem interações)` : m.daysSinceLastContact}`,
    `Win rate do responsável: ${
      m.assigneeWinRate === null ? `${INSUFFICIENT} (sem histórico de fechamento)` : `${m.assigneeWinRate}% (${m.assigneeClosedCount} deals fechados)`
    }`,
  ].join('\n');
}

export const dealScoringService = {
  /**
   * Compute (via AI) and persist the close-propensity score for a deal.
   * Returns the stored result. Throws 404 if deal missing, 503 if AI fails.
   */
  async computeAndStore(tenantId: string, dealId: string): Promise<DealAIScore> {
    if (!isAIEnabled()) throw aiUnavailableError();

    const built = await buildDealMetrics(tenantId, dealId);
    if (!built) {
      throw Object.assign(new Error('Deal não encontrado'), { statusCode: 404, isOperational: true });
    }

    const model = getActiveModel();
    if (!model) throw aiUnavailableError();

    const factsText = renderMetrics(built.metrics);

    try {
      const startedAt = Date.now();
      // generateObject generic inference (model + zod) triggers TS2589 under
      // moduleResolution:node — call untyped; schema still validates at runtime.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result = await (generateObject as any)({
        model,
        schema: scoreSchema,
        system: SCORE_SYSTEM_PROMPT,
        prompt: factsText,
        temperature: 0.3,
      });
      const object = result.object as z.infer<typeof scoreSchema>;

      logAiUsage({
        feature: 'deal-score',
        tenantId,
        dealId,
        latencyMs: Date.now() - startedAt,
        tokens: result.usage?.totalTokens,
        promptTokens: result.usage?.inputTokens,
        completionTokens: result.usage?.outputTokens,
        provider: resolveProviderConfig()?.provider,
      });

      const score = Math.max(0, Math.min(100, Math.round(object.score)));
      const factors: ScoreFactor[] = (object.factors || []).slice(0, 3).map((f) => ({
        label: f.label,
        detail: f.detail,
      }));
      const updatedAt = new Date();

      await prisma.deal.update({
        where: { id: dealId },
        data: {
          aiScore: score,
          aiScoreUpdatedAt: updatedAt,
          aiScoreFactors: factors as unknown as object,
        },
      });

      return { score, factors, updatedAt: updatedAt.toISOString(), aiGenerated: true };
    } catch (error: any) {
      if (error?.statusCode === 404) throw error;
      logger.warn('Deal AI score generation failed', { dealId, error: error?.message });
      throw aiUnavailableError();
    }
  },

  /**
   * Return the stored score for a deal, computing it on first access when absent.
   * The route uses this so a deal that was never scored still returns a value.
   */
  async getOrCompute(tenantId: string, dealId: string): Promise<DealAIScore> {
    const deal = await prisma.deal.findFirst({
      where: { id: dealId, tenantId },
      select: { aiScore: true, aiScoreUpdatedAt: true, aiScoreFactors: true },
    });
    if (!deal) {
      throw Object.assign(new Error('Deal não encontrado'), { statusCode: 404, isOperational: true });
    }

    if (deal.aiScore !== null && deal.aiScoreUpdatedAt) {
      return {
        score: deal.aiScore,
        factors: (deal.aiScoreFactors as unknown as ScoreFactor[]) || [],
        updatedAt: deal.aiScoreUpdatedAt.toISOString(),
        aiGenerated: true,
      };
    }

    return this.computeAndStore(tenantId, dealId);
  },
};
