-- AI Sales Assistant (Story AI-2.1): close-propensity score fields on Deal.
-- Generated by AI, recalculated weekly (scoreDeals job) and on demand.
ALTER TABLE "Deal" ADD COLUMN "aiScore" DOUBLE PRECISION;
ALTER TABLE "Deal" ADD COLUMN "aiScoreUpdatedAt" TIMESTAMP(3);
ALTER TABLE "Deal" ADD COLUMN "aiScoreFactors" JSONB;
